export { default as NavBar } from "./NavBar/NavBar";
export { default as StatsTables } from "./StatsTables/StatsTables";
export { default as QuickInfo } from "./QuickInfo/QuickInfo";
export { default as Map } from "./Map/Map";
export { default as InfoCard } from "./QuickInfo/InfoCard";
export { default as LineGraph } from "./LineGraph/LineGraph";
export { default as Chart } from "./Chart/Chart";
export { default as GeoBoard } from "./GeoBoard/GeoBoard";
export { default as Quizz } from "./Quiz/Quiz";
